on: [push, workflow_dispatch]
jobs:
    minify:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v2
            - name: minify
              uses: nizarmah/auto-minify@v2.1
              with:
                    overwrite: true
                    directory: 'scripts'
                    output: 'dist'
            - name: commit
              uses: stefanzweifel/git-auto-commit-action@v5
              with:
                    commit_message: "Github Action: Auto Minified Scripts"
                    branch: ${{ github.ref }}
